const isNull = require("./isNull.test");
const isUndefined = require("./isUndefined.test");
const isObjectTest = require("./isObject.test");
const isFunctionTest = require("./isFunction.test");
const isObjectLikeTest = require("./isObjectLike.test");
const isPlainObjectTest = require("./isPlainObject.test");
const isArrayLikeTest = require("./isArrayLike.test");
const isArrayTest = require("./isArray.test");
const isStringTest = require("./isString.test");
const isBooleanTest = require("./isBoolean.test");
const isNumberTest = require("./isNumber.test");

isNull();
isUndefined();
isObjectTest();
isFunctionTest();
isObjectLikeTest();
isPlainObjectTest();
isArrayLikeTest();
isArrayTest();
isStringTest();
isBooleanTest();
isNumberTest();
